ALTER TABLE messages ADD COLUMN status TEXT NOT NULL DEFAULT 'pending';

ALTER TABLE messages ADD COLUMN channel_type TEXT;

ALTER TABLE scenes ADD COLUMN description TEXT NOT NULL DEFAULT '';

ALTER TABLE scenes ADD COLUMN context TEXT NOT NULL DEFAULT '';

ALTER TABLE scenes ADD COLUMN agent_id TEXT;

ALTER TABLE scenes ADD COLUMN status TEXT NOT NULL DEFAULT 'running';

ALTER TABLE scenes ADD COLUMN purpose TEXT NOT NULL DEFAULT '';

ALTER TABLE scenes ADD COLUMN kbs TEXT NOT NULL DEFAULT '[]';

ALTER TABLE scenes ADD COLUMN skills TEXT NOT NULL DEFAULT '[]';

ALTER TABLE scenes ADD COLUMN tools TEXT NOT NULL DEFAULT '[]';

ALTER TABLE scenes ADD COLUMN channels TEXT NOT NULL DEFAULT '[]';

ALTER TABLE scenes ADD COLUMN llm_config TEXT NOT NULL DEFAULT '{}';

ALTER TABLE scenes ADD COLUMN visibility TEXT NOT NULL DEFAULT 'private';

ALTER TABLE scenes ADD COLUMN updated_at TEXT NOT NULL DEFAULT (datetime('now'));

ALTER TABLE scenes ADD COLUMN archived_at TEXT;
