import {
  getModelsByProvider,
  getModel,
  getProvider,
  providers,
  type Model,
} from "modelpedia"

// Map CocoCat internal provider names → modelpedia provider IDs
// Only non-identity mappings; direct matches fall through via || cocoName
const PROVIDER_MAP: Record<string, string> = {
  gemini: "google",
  dashscope: "alibaba",
  "aws-bedrock": "amazon",
}

// All modelpedia provider IDs for fast lookup
const MODELPEDIA_IDS = new Set(providers.map((p) => p.id))

// ── Runtime catalog (updated by update-model-catalog.py) ──

interface CatalogJson {
  providers: Array<{ id: string; name: string }>
  models: Model[]
  updated: string
}

let _catalogJson: CatalogJson | null = null
let _catalogPromise: Promise<void> | null = null

/** Load the latest catalog JSON (generated by scripts/update-model-catalog.py). */
export async function loadCatalogJson(): Promise<void> {
  if (_catalogJson) return
  if (_catalogPromise) return _catalogPromise
  _catalogPromise = fetch("/model-catalog.json")
    .then((r) => r.json())
    .then((data: CatalogJson) => {
      _catalogJson = data
    })
    .catch(() => {
      // JSON not available, fall back to npm package data only
    })
  return _catalogPromise
}

/** Return the merged model list for a provider — npm package + JSON catalog. */
function getMergedModels(mpId: string): Model[] {
  const npmModels = getModelsByProvider(mpId) || []
  const npmIds = new Set(npmModels.map((m) => m.id))
  const extra: Model[] = []

  if (_catalogJson) {
    for (const m of _catalogJson.models) {
      if (m.provider === mpId && !npmIds.has(m.id)) {
        extra.push(m)
      }
    }
  }

  return [...npmModels, ...extra]
}

/**
 * Check if modelpedia covers a given CocoCat provider.
 */
export function isProviderSupported(cocoName: string): boolean {
  const mpId = PROVIDER_MAP[cocoName] || cocoName
  return MODELPEDIA_IDS.has(mpId)
}

/**
 * Get all non-deprecated models for a CocoCat provider from modelpedia.
 * Sorted: active → preview → undefined status.
 * Returns empty array if provider not covered.
 */
export function getCatalogModels(cocoName: string): Model[] {
  const mpId = PROVIDER_MAP[cocoName] || cocoName
  const all = getMergedModels(mpId)
  if (!all || all.length === 0) return []

  const filtered = all.filter((m) => m.status !== "deprecated")
  const order: Record<string, number> = { active: 0, preview: 1 }
  filtered.sort((a, b) => {
    const oa = order[a.status || ""] ?? 2
    const ob = order[b.status || ""] ?? 2
    return oa - ob
  })
  return filtered
}

/**
 * Get full metadata for a single model.
 */
export function getCatalogMeta(
  cocoName: string,
  modelId: string,
): Model | undefined {
  const mpId = PROVIDER_MAP[cocoName] || cocoName
  return getModel(mpId, modelId)
}

/**
 * Get provider metadata from modelpedia (api_url, docs_url, etc.).
 */
export function getCatalogProvider(cocoName: string) {
  const mpId = PROVIDER_MAP[cocoName] || cocoName
  return getProvider(mpId)
}
