export const TOOL_DISPLAY_NAMES: Record<string, string> = {
  read_file:          "读取文件",
  write_file:         "写入文件",
  edit_file:          "编辑文件",
  list_dir:           "浏览目录",
  bash:               "执行命令",
  glob:               "文件搜索",
  grep:               "内容搜索",
  web_search:         "网页搜索",
  web_fetch:          "获取网页",
  browser:            "浏览器操作",
  define_dag:         "定义任务",
  append_stage:       "追加阶段",
  update_dag:         "更新任务",
  dispatch_task:      "派发任务",
  check_tasks:        "检查进度",
  stop_task:          "停止任务",
  recall:             "记忆搜索",
  pin:                "固定事实",
  unpin:              "取消固定",
  record_experience:  "记录经验",
  recall_experience:  "回顾经验",
  cron:               "定时任务",
  current_status:     "状态检查",
  wait:               "等待",
  sub_agent:          "子代理",
}
