channels:
  discord:
    config: {}
    enabled: false
  feishu:
    config:
      app_id: test
      app_secret: secret
    enabled: true
  telegram:
    config: {}
    enabled: false
  web_api:
    config: {}
    enabled: false
  wechat:
    config: {}
    enabled: false
  weixin:
    config: {}
    enabled: true
